#!/bin/bash -ex
#
# setup-bootloader - Configure bootloader for Rocky Linux 9
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Ensure grub is properly configured
if [ -d /boot/grub2 ]; then
    # Update grub configuration
    grub2-mkconfig -o /boot/grub2/grub.cfg
fi

# Ensure the system uses NetworkManager
if [ -f /etc/NetworkManager/NetworkManager.conf ]; then
    # Make sure NetworkManager manages all devices
    sed -i 's/^managed=false/managed=true/' /etc/NetworkManager/NetworkManager.conf
fi
